const ACTION_TYPES = {
  ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_ERROR: 'ADD_TASK_ERROR',

  GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',

  SET_TASK_DONE_REQUEST: 'SET_TASK_DONE_REQUEST',
  SET_TASK_DONE_SUCCESS: 'SET_TASK_DONE_SUCCESS',
  SET_TASK_DONE_ERROR: 'SET_TASK_DONE_ERROR',

  CLEAR_ERROR: 'CLEAR_ERROR',
};

export default ACTION_TYPES;
